### ISSUE TITLE
Remove Search button when searching with date

### ISSUE THREAD

**Issue by junnengsoo** [fabkoh/vms-ac-ui-next#74]

**Comment by yongning0310** [comment]
Currently, our interface has two methods to retrieve entities from the database: a "Search" button and a "Date Filter." Here's how they currently function:

"Search" Button: When clicked, this button fetches a random set of entities from the database. The number of entities retrieved is arbitrary and not defined by any specific criteria.

"Date Filter": This option gives the impression that it functions similarly to the "Search" button. However, in reality, it only filters entities based on the date among those already loaded on the frontend. It doesn't fetch new entities from the database that match the date criteria.

The expected workflow should be different for the "Date Filter." Ideally, when a user applies this filter, it should retrieve a new, arbitrary set of entities from the database that match the specified date criteria, similar to how the "Search" button retrieves entities but filtered by the selected date.
